kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  #namespace: "datadog"
spec:
  global:
    clusterName: "argus"
    site: "us5.datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: "otel-grpc"
        - containerPort: 4318
          hostPort: 4318
          name: "otel-http"
  override:
    nodeAgent:
      env:
        - name: "DD_HOSTNAME_TRUST_UTS_NAMESPACE"
          value: "true"
    clusterAgent:
      containers:
        cluster-agent:
          env:
            - name: "DD_HOSTNAME_TRUST_UTS_NAMESPACE"
              value: "true"
