apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: grafana
- kind: ServiceAccount
  name: prometheus
  namespace: default
- kind: ServiceAccount
  name: prometheus
  namespace: kube-system
- kind: ServiceAccount
  name: prometheus
  namespace: blackbox-exporter
- kind: ServiceAccount
  name: prometheus
  namespace: prometheus
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: prometheus

