apiVersion: v1
data:
  additional_scrape_configs.yml: |
    scrape_configs:
      - job_name: 'blackbox_exporter'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://www.google.com
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - target_label: __address__
          replacement: blackbox-exporter-service.blackbox-exporter:9115
        - source_labels: [__param_target]
          target_label: instance
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: blackbox-scrape
  namespace: prometheus
