kind: Deployment
apiVersion: apps/v1
metadata:
  name: raspi-promql
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prom-raspi
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/
      volumes:
        - name: config
          hostPath:
            path: /apps/


