kind: Namespace
apiVersion: v1
metadata:
  name: prometheus
---
kind: Service
apiVersion: v1
metadata:
  name: prom-internal-service
  namespace: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090


