apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: argus
servers: 1
agents: 1
subnet: "175.28.0.0/16"
volumes:
  - volume: /mnt/Data/development/kubernetes/argus/argus-observability-lab/worker:/app
    nodeFilters:
      - server:0
      - agent:*
        #ports:
        #  - port: 3110:3110
    #    nodeFilters:
    #- loadbalancer
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
          - agent:*
