kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  labels:
    app: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: test-raspi
          image: alpine
          volumeMounts:
            - name: logging
              mountPath: /app/log
          command:
            [
              "sh",
              "-c",
              'while true; do echo "Writting to log. Timestamp: `date`" >> /app/log/app.log; sleep 5; done;',
            ]
          imagePullPolicy: IfNotPresent
        - name: fluentd
          image: fluentd
          volumeMounts:
            - name: logging
              mountPath: /app/log
          env:
            - name: FLUENT_CONF
              value: |
                <source>
                  @type tail
                  path /app/log/app.log
                  pos_file /app/log/app.log.pos
                  tag app.log
                </source>

      volumes:
        - name: logging
          emptyDir: {}
