kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  labels:
    app: test
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: test-raspi
          image: alpine
          command: ["sleep","infinity"]
          imagePullPolicy: IfNotPresent


